### PR TITLE
Improved pofile screen

### LINKED ISSUE #116: Revamp the profile screen
# Description
Revamp the screen, the UI is completely up to you (tho it will require my approval). This would also require some refactoring and some fixing with the updation logic (might turn this into a bonus issue).

# Relevant files
- `Profile.dart`

# Screenshot

### PR DESCRIPTION
**Pull request by Pranav108**
## Program
- [x] CodePeak
- [ ] Script Winter of Code
- [ ] None

## Issue
Fixes #116 

## Description
Improved the UI for Profile screen and removed email edit section from there .

## Type of change
You can write manually also

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Screenshot
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Pranav108** [comment]
I tried my best to not to leave any error behind, but let me know if something is.

**Comment by Saransh-cpp** [comment]
@Pranav108 please resolve the conflicts

**Comment by Pranav108** [comment]
> @Pranav108 please resolve the conflicts

this option is disabled for me
image

**Comment by Saransh-cpp** [comment]
image

You need to pull in the latest code -
```
git pull <remote_name> master
```

**Pull request closed without merging**
