### PR TITLE
Resolved Home.dart(Issue #68)

### PR DESCRIPTION
**Pull request by raviyadav17**
Fixed And Resolved Issue #68

### CODE REVIEW

**Comment by raviyadav17** [comment]
Problem with merging. Even after following your steps and even both branches have same files. :(

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
@raviyadav17, please revert back the changes in `Register.dart`, they are not needed.

**Comment by raviyadav17** [comment]
> @raviyadav17, please revert back the changes in `Register.dart`, they are not needed.

In master or the resolved branch??
can you also tell the command to revert back changes.

**Comment by Saransh-cpp** [comment]
> In master or the resolved branch?? can you also tell the command to revert back changes.

As the changes you made are small, a quick fix would be to copy [`Register.dart`](https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Screens/Register.dart) and past it in place of your local `Register.dart` screen. Dame for the `Home` screen. You can make the changes after that!

**Pull request closed without merging**
