### PR TITLE
Issue 45 login without credentials

### LINKED ISSUE #45: Logging in with Invalid Credentials
The app lets us login with invalid email and password. We can put any non-empty email like '123' and any password with more than 6 characters and sign in to the app. But the home screen and cart screen will display an error as shown ->

### PR DESCRIPTION
**Pull request by mortal-ghost**
## Issue
Fixes #45 

## Description

Only one change in the lib/Screens/LoginPage.dart 
Home screen was pushed on validating form conditions without validating the credentials.
Minor change to lib/Provider/user.dart regarding the google sign in issue. Calling the createUser function on signing in.

## Type of change
You can write manually also

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] The app runs properly
- [X] I have performed a self-review of my own code
- [X] I have formatted and commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
@mortal-ghost, please merge in master of my repository.

**Comment by mortal-ghost** [comment]
> @mortal-ghost, please merge in master of my repository.

Can you please help me regarding this?

**Comment by Saransh-cpp** [comment]
And no need to close this PR, you can keep pushing commits in your branch and they will automatically appear in this PR :)

**Comment by mortal-ghost** [comment]
> > Can you please help me regarding this?
> 
> Can you tell me what `git remote -v` shows you?

ss1

**Comment by Saransh-cpp** [comment]
Great! Please switch to the branch on which you are working and execute the following -

```
git pull upstream master
```

This will fetch and merge the master branch from the upstream remote (my repository) into your current branch. It will not merge automatically if there are some merge conflicts, which you will have to handle clear yourself.

Let me know if you face any difficulties!

**Comment by mortal-ghost** [comment]
Ok , I resolved a lot of conflicts (:laughing:) and made a commit with this error fixed in. Can you please confirm if this is fine now?

**Comment by Saransh-cpp** [comment]
@mortal-ghost, did you forget to push? :)

**Comment by mortal-ghost** [comment]
No I pushed the changes. I am getting the option to create a new PR. Should I just create a new one?

**Comment by Saransh-cpp** [comment]
Yes, create a new one!

**Pull request closed without merging**
