### PR TITLE
Issue 89 register screen error

### LINKED ISSUE #89: Error on register screen
# Description
The register screen throws an error anytime it is opened.

# Relevant files
lib/Screens/Register.dart

# Screenshot
Screenshot_1639336563

### PR DESCRIPTION
**Pull request by mortal-ghost**
## Program
- [X] CodePeak
- [ ] Script Winter of Code
- [ ] None

## Issue
Fixes #89 

## Description

The form widget in the lib/Screens/Register.dart was duplicated which was causing the error. The duplicate form on top of the original form widget is removed.

## Type of change
You can write manually also

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Screenshot
Screenshot_1639411107

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] The app runs properly
- [X] I have performed a self-review of my own code
- [X] I have formatted and commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by msramesh2k1 — APPROVED** [review]
Hey @mortal-ghost , Great Job . Code works fine

**Comment by msramesh2k1** [comment]
@Saransh-cpp I checked the code it works fine , you can merge now

**Comment by Saransh-cpp** [comment]
@all-contributors please add @msramesh2k1 for review, mentoring

**Comment by Saransh-cpp** [comment]
@all-contributors please add @msramesh2k1 for review, mentoring

**Pull request merged**
