### PR TITLE
Fixes: #115  fixed renderflex overflow in cart page.

### LINKED ISSUE #115: Renderflex overflow in cart screen
# Description
Make the screen dynamic.

# Relevant files
- `YourOrders.dart`

# Screenshot

### PR DESCRIPTION
**Pull request by noman2002**
## Program
- [ ] CodePeak
- [x] Script Winter of Code
- [ ] None

## Issue
Fixes #115 

## Description
fixed renderflex overflow by adding single childscrollview

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
@noman2002, please merge the master branch of my repository

**Comment by noman2002** [comment]
> @noman2002, please merge the master branch of my repository

I am unble to merge it. Can you please help me out.

**Comment by Saransh-cpp** [comment]
> I am unable to merge it. Can you please help me out. It is giving lots of error after pulling it from upstream.

Yes, you will have to solve those conflicts manually.

**Comment by noman2002** [comment]
Should I close this PR and create a new one ?

**Comment by Saransh-cpp** [comment]
> Should I close this PR and create a new one ?

No, you can push your commits and they will automatically appear on this PR.

**Comment by noman2002** [comment]
There are a lot of conflicts, I am thinking to re fork the repo and fix the issue again and create a new PR. Should I do that.

**Comment by Saransh-cpp** [comment]
> There are a lot of conflicts, I am thinking to re fork the repo and fix the issue again and create a new PR. Should I do that.

Yes, feel free to do that :)

**Comment by noman2002** [comment]
okkk I am creating a new PR. Please merge that

**Pull request closed without merging**
