### PR TITLE
Issue fix 111

### LINKED ISSUE #111: deprecated `firebase_admob` package
# Description
In this app we have implemented `firebase_admob` package for showing mobile ads on myCart screen, which is deprecated now, instead we should use `google_mobile_ads` package. 

# Relevant files
`lib/Screens/YourOrders.dart`

# Screenshot
image

# References
[reference](https://pub.dev/documentation/firebase_admob/latest/#:~:text=The%20firebase_admob%20plugin%20will%20be,Mobile%20Ads%20SDK%20for%20Flutter.&text=It%20also%20supports%20displaying%20banner,overlayed%20over%20all%20app%20content.)

### PR DESCRIPTION
**Pull request by rajoriaakash**
## Program
- [ ] CodePeak
- [x] Script Winter of Code
- [ ] None

## Issue
Fixes #111 

## Description

Integrate google mobile ads SDK into the project and display banner ad on orders screen.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Screenshot
Screenshot of the fix if required.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rajoriaakash** [comment]
Please merge it soon :) otherwise, I'll have to again resolve merge conflicts.

**Review by Procoder16 — APPROVED** [review]
Commit looks good to me!
But from next time, make sure you are also providing a screenshot and attach it to your commit message.

**Comment by rajoriaakash** [comment]
> Commit looks good to me! But from next time, make sure you are also providing a screenshot and attach it to your commit message.

Alright!

**Comment by rajoriaakash** [comment]
Any suggestions/ issues on backend? I would gladly like to try.

**Review by Saransh-cpp — APPROVED** [review]
Sorry for the extreme delay 🙂

**Pull request merged**
