### PR TITLE
Fix  Stylify the README file #9 

### PR DESCRIPTION
**Pull request by Youspeakcubic**
##Updating read me

- [x] Making logo full width of docs
- [x] Adding emojis to headers
- [x] Fixing numbering/spelling issues
- [x] center aligning all images

### Logo fix:

logofix
Made the logo span the whole read me for a much cleaner look
### added emojis to headers:

emojiFix

### Center align images:

alignfix
Aligned all images in the read me to the center as to look more clean.

### Fixing numbering and spelling:

Pretty self explanatory, fixed spelling issues throughout the read me as well as the numbers in the wrong order with some of the instructions. I also condensed some sections to make it easier to read.

@Saransh-cpp Please let me know if anything else needs to be changed, awaiting your review 👍 .

### CODE REVIEW

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
Awesome work, thanks @Youspeakcubic! Looks good to me. Just some minor comments below, you can commit them directly from GitHub

**Review by Youspeakcubic — COMMENTED** [review]
Committed suggested changes

**Comment by Youspeakcubic** [comment]
I committed your suggested changes, Do let me know if any other work is needed on the app.

**Comment by Saransh-cpp** [comment]
Thanks @Youspeakcubic! Merging!

**Review by Saransh-cpp — APPROVED** [review]

**Comment by Saransh-cpp** [comment]
@all-contributors please add @Youspeakcubic  for content, documentation, and design

**Pull request merged**
