### PR TITLE
Issue 45 login without credentials

### LINKED ISSUE #45: Logging in with Invalid Credentials
The app lets us login with invalid email and password. We can put any non-empty email like '123' and any password with more than 6 characters and sign in to the app. But the home screen and cart screen will display an error as shown ->

### PR DESCRIPTION
**Pull request by mortal-ghost**
## Issue
Fixes #45 
Fixed logging in with invalid credentials

## Description

2 files changed -> lib/Screens/LoginPage.dart and lib/Screens/Register.dart
else statement added with if statement in login and register buttons.
 
## Type of change
You can write manually also

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] The app runs properly
- [X] I have performed a self-review of my own code
- [X] I have formatted and commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
@mortal-ghost, please resolve the conflicts

**Comment by mortal-ghost** [comment]
Can you please confirm if this works now?

**Review by Saransh-cpp — APPROVED** [review]
Oh damn, this fixed this issue? 🤣

Hard to spot though, great work!

**Comment by Saransh-cpp** [comment]
@all-contributors please add @mortal-ghost for code

**Comment by mortal-ghost** [comment]
> Oh damn, this fixed this issue? rofl
> 
> Hard to spot though, great work!

Yes, same reaction :rofl: . I checked the sign in function and what not. This was the problem .

**Pull request merged**
