### PR TITLE
Issue 02 readme add

### LINKED ISSUE #2: Add all the screens to `README`
## Description
Add a compiled image of all the screens in the README file.

## References
- https://github.com/smaranjitghose/DocLense#app-screens
- https://app-mockup.com/

### PR DESCRIPTION
**Pull request by hurshh**
## Issue
Fixes #2 

## Description
Added all screens to README.md and gave them catchy titles

## Type of change

-  added png of all app screens

## Screenshot

image

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] The app runs properly
- [X] I have performed a self-review of my own code
- [X] I have formatted and commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
Thanks, @hurshh! Looks good! Could you add the devices in the images, and replace the `Quiz` screen with the `favorites` screen (after adding a few items to favorites).

**Comment by hurshh** [comment]
i have changed that screen

**Comment by Saransh-cpp** [comment]
@hurshh, the screens are not fitting well on the device. Please use a different device in the image, or use a different device's screenshot.

**Comment by hurshh** [comment]
ok, improved that

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @hurshh! Looks great! Which program are you a part of?

**Comment by Saransh-cpp** [comment]
@all-contributors please add @hurshh for docs

**Pull request merged**
